### ISSUE TITLE
Dropdown menubar doesn't work

### ISSUE THREAD

**Issue by lspitaels** [divio/django-cms-explorer#8]
Hi,

I added children pages to one page in the admin but it doesn't show the dropdown menu to access to the other pages.
Do you have an idea why I have this issue?
PS: I published all the pages.

Cheers,
Laurent

**Comment by FinalAngel** [comment]
@lspitaels the menu is set to show only the first level in ``base.html``:

```
{% show_menu 0 0 0 0 "includes/menu/navigation.html" %}
```

You would need to adapt that part and eventually also the html/styles.

**Comment by lspitaels** [comment]
Thanks a lot. It works.

**Comment by FinalAngel** [comment]
You are very welcome @lspitaels
